export const STATUS_COLORS: Record<string, string> = {
  open: 'bg-blue-500/10 text-blue-300 border border-blue-500/30',
  new: 'bg-blue-500/10 text-blue-300 border border-blue-500/30',
  assigned: 'bg-indigo-500/10 text-indigo-300 border border-indigo-500/30',
  in_progress: 'bg-yellow-500/10 text-yellow-300 border border-yellow-500/30',
  awaiting_quote: 'bg-orange-500/10 text-orange-300 border border-orange-500/30',
  service_request: 'bg-cyan-500/10 text-cyan-300 border border-cyan-500/30',
  scheduled: 'bg-green-500/10 text-green-300 border border-green-500/30',
  on_hold: 'bg-gray-500/10 text-gray-300 border border-gray-500/30',
  pending_board_review: 'bg-red-500/10 text-red-300 border border-red-500/30',
  approved: 'bg-emerald-500/10 text-emerald-300 border border-emerald-500/30',
  approved_with_conditions: 'bg-amber-500/10 text-amber-300 border border-amber-500/30',
  under_review_with_architect: 'bg-violet-500/10 text-violet-300 border border-violet-500/30',
  denied: 'bg-rose-500/10 text-rose-300 border border-rose-500/30',
  closed: 'bg-gray-500/5 text-gray-400 border border-gray-500/20',
  monitored: 'bg-teal-500/10 text-teal-300 border border-teal-500/30',
  cancelled: 'bg-gray-500/5 text-gray-400 border border-gray-500/20',
  past_due: 'bg-red-600/10 text-red-200 border border-red-600/30',
  notified: 'bg-blue-500/10 text-blue-300 border border-blue-500/30',
  fined: 'bg-red-500/10 text-red-300 border border-red-500/30',
  resolved: 'bg-emerald-500/10 text-emerald-300 border border-emerald-500/30',
}

export const STATUS_LABELS: Record<string, string> = {
  open: 'Open',
  new: 'New',
  assigned: 'Assigned',
  in_progress: 'In Progress',
  awaiting_quote: 'Awaiting Quote',
  service_request: 'Service Request',
  scheduled: 'Scheduled',
  on_hold: 'On Hold',
  pending_board_review: 'Pending Board Review',
  approved: 'Approved',
  approved_with_conditions: 'Approved w/ Conditions',
  under_review_with_architect: 'Under Review by ARC',
  denied: 'Denied',
  closed: 'Closed',
  monitored: 'Monitored',
  cancelled: 'Cancelled',
  past_due: 'Past Due',
  notified: 'Notified',
  fined: 'Fined',
  resolved: 'Resolved',
}

export const CATEGORY_COLORS: Record<string, string> = {
  arc_request: 'bg-violet-500/10 text-violet-300',
  work_order: 'bg-blue-500/10 text-blue-300',
  violation: 'bg-red-500/10 text-red-300',
  landscaping: 'bg-green-500/10 text-green-300',
  gutter: 'bg-cyan-500/10 text-cyan-300',
  roofing: 'bg-amber-500/10 text-amber-300',
  siding: 'bg-orange-500/10 text-orange-300',
  irrigation: 'bg-teal-500/10 text-teal-300',
  drainage: 'bg-indigo-500/10 text-indigo-300',
  painting: 'bg-pink-500/10 text-pink-300',
  general_repair: 'bg-stone-500/10 text-stone-300',
  governance: 'bg-purple-500/10 text-purple-300',
  other: 'bg-gray-500/10 text-gray-300',
}

export const CATEGORY_LABELS: Record<string, string> = {
  arc_request: 'ARC Request',
  work_order: 'Work Order',
  violation: 'Violation',
  landscaping: 'Landscaping',
  gutter: 'Gutter',
  roofing: 'Roofing',
  siding: 'Siding',
  irrigation: 'Irrigation',
  drainage: 'Drainage',
  painting: 'Painting',
  general_repair: 'General Repair',
  governance: 'Governance',
  other: 'Other',
}

export const DECISION_COLORS: Record<string, string> = {
  approved: 'bg-emerald-500/10 text-emerald-300 border border-emerald-500/30',
  approved_with_conditions: 'bg-amber-500/10 text-amber-300 border border-amber-500/30',
  denied: 'bg-rose-500/10 text-rose-300 border border-rose-500/30',
  no_approval_needed: 'bg-blue-500/10 text-blue-300 border border-blue-500/30',
  pending: 'bg-yellow-500/10 text-yellow-300 border border-yellow-500/30',
  info_requested: 'bg-orange-500/10 text-orange-300 border border-orange-500/30',
}

export const DECISION_LABELS: Record<string, string> = {
  approved: 'Approved',
  approved_with_conditions: 'Approved with Conditions',
  denied: 'Denied',
  no_approval_needed: 'No Approval Needed',
  pending: 'Pending',
  info_requested: 'Info Requested',
}

export const EMAIL_CLASSIFICATION_LABELS: Record<string, string> = {
  noise: 'Noise',
  property_report: 'Property Report',
  wo_status_report: 'WO Status Report',
  arc_form_submission: 'ARC Form Submission',
  arc_manager_reply: 'ARC Manager Reply',
  arc_process_discussion: 'ARC Process Discussion',
  arc_form_forward: 'ARC Form Forward',
  wo_form: 'WO Form',
  hppr_form: 'HPPR Form',
  board_email: 'Board Email',
  josh_direct: 'Josh Direct',
  homeowner_direct: 'Homeowner Direct',
  governance: 'Governance',
  ops_alert: 'Ops Alert',
  unclassified: 'Unclassified',
}

export const PRIORITY_ORDER: Record<string, number> = {
  urgent: 4,
  high: 3,
  medium: 2,
  low: 1,
}
